name: check for flake updates
on: { workflow_dispatch, schedule: [cron: '0 0 * * *'] }
jobs:
  check-for-updates:
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.NIX_UPDATES_PAT }}
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-trusted-public-keys = adaptivereader.cachix.org-1:AoiyYyEjcXjS0Ci77VIubWfUKOusjweA7S43UYkC/sw= cache.g7c.us:dSWpE2B5zK/Fahd7npIQWM4izRnVL+a4LiCAnrjdoFY=
            extra-substituters = https://adaptivereader.cachix.org https://cache.g7c.us
      - run: nix flake update
      - uses: peter-evans/create-pull-request@v8.1.0
        id: pr
        with:
          author: Ben Duggan <benaduggan@gmail.com>
          base: main
          branch: updates-nix
          commit-message: 'Update nix pin'
          title: '[BOT-000]: nix updates'
          token: ${{ secrets.NIX_UPDATES_PAT }}
      - if: ${{ steps.pr.outputs.pull-request-number }}
        run: gh pr merge --auto --squash ${{ steps.pr.outputs.pull-request-url }}
